version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.1
    - 4.15.2
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
    - 7.5.0
    - 7.6.0
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.9
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.9
  - dependency-name: vuex
    versions:
    - 3.6.0
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.9
